In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("chipotle.csv")

In [11]:
df.head()
# get rid of the col order_id
df.drop("order_id", axis = 1, inplace = True)

In [12]:
df.columns

Index(['quantity', 'item_name', 'choice_description', 'item_price'], dtype='object')

In [13]:
df.rename(columns={"item_price":"order_price"}, inplace=True)

In [14]:
# what is the most expensive order what was ordered?
df["order_price"] = df["order_price"].apply(lambda x : float(x.strip("$")))

In [12]:
df[df["order_price"] == df["order_price"].max()]

      quantity                     item_name choice_description  order_price
3598        15  Chips and Fresh Tomato Salsa                NaN        44.25

In [15]:
df['item_name'].nunique()

50

In [17]:
# How many unique items are in the data set ---> item_name
df['item_name'].unique()
# how many times people order 'Chicken Bowl'

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [20]:
df[df["item_name"]=='Chicken Bowl']["quantity"].sum()

761

In [32]:
# # How many time people ordered more than 1 'Canned Soda'
# 1. get all orders of Canned Soda
cs = df[df["item_name"]=='Canned Soda']
# 2. Then check quantity
cs[cs["quantity"]>1].count().iloc[0]

20

In [25]:
condition1 = df["item_name"].str.contains("canned soda", case=False)
condition2 = df["quantity"]>1
df[condition1 & condition2].count().iloc[0]

20

In [36]:
# what is 'Chicken Bowl'total revenue
chicken_bowl_revenue=df[df["item_name"] == "Chicken Bowl"]["order_price"].sum()

In [37]:
total_revenue = df["order_price"].sum()

In [38]:
chicken_bowl_revenue_percent = chicken_bowl_revenue / total_revenue *100
chicken_bowl_revenue_percent

21.283176657731442

In [44]:
revenue = df.groupby("item_name")[["order_price"]].sum()
revenue.sort_values("order_price", ascending=False, inplace=True)

In [47]:
revenue["Per"] = revenue["order_price"]/total_revenue*100
revenue["Per"] = revenue["Per"].round(2)
revenue

                                       order_price    Per
item_name
Chicken Bowl                               7342.73  21.28
Chicken Burrito                            5575.82  16.16
Steak Burrito                              3851.43  11.16
Steak Bowl                                 2260.19   6.55
Chips and Guacamole                        2201.04   6.38
Chicken Salad Bowl                         1228.75   3.56
Chicken Soft Tacos                         1108.09   3.21
Veggie Burrito                              934.77   2.71
Barbacoa Burrito                            894.75   2.59
Veggie Bowl                                 867.99   2.52
Carnitas Bowl                               736.71   2.14
Barbacoa Bowl                               672.36   1.95
Carnitas Burrito                            597.83   1.73
Steak Soft Tacos                            536.05   1.55
Chips                                       494.34   1.43
Chicken Crispy Tacos                        472.13   1.37
Canned Soft Drink                           438.75   1.27
Carnitas Soft Tacos                         375.94   1.09
Chips and Fresh Tomato Salsa                361.36   1.05
Steak Crispy Tacos                          357.34   1.04
6 Pack Soft Drink                           356.95   1.03
Steak Salad Bowl                            343.59   1.00
Bottled Water                               302.56   0.88
Barbacoa Soft Tacos                         250.46   0.73
Side of Chips                               185.90   0.54
Veggie Salad Bowl                           182.50   0.53
Chips and Tomatillo Red Chili Salsa         147.50   0.43
Canned Soda                                 137.34   0.40
Chips and Tomatillo Green Chili Salsa       132.75   0.38
Barbacoa Crispy Tacos                       120.21   0.35
Barbacoa Salad Bowl                         106.40   0.31
Nantucket Nectar                             98.31   0.28
Chicken Salad                                81.09   0.24
Chips and Tomatillo-Green Chili Salsa        78.87   0.23
Carnitas Crispy Tacos                        77.96   0.23
Veggie Soft Tacos                            73.96   0.21
Chips and Roasted Chili Corn Salsa           67.85   0.20
Izze                                         67.80   0.20
Carnitas Salad Bowl                          66.34   0.19
Chips and Tomatillo-Red Chili Salsa          59.75   0.17
Veggie Salad                                 50.94   0.15
Burrito                                      44.40   0.13
Chips and Roasted Chili-Corn Salsa           43.02   0.12
Steak Salad                                  35.66   0.10
Bowl                                         29.60   0.09
Salad                                        14.80   0.04
Crispy Tacos                                 14.80   0.04
Carnitas Salad                                8.99   0.03
Veggie Crispy Tacos                           8.49   0.02
Chips and Mild Fresh Tomato Salsa             3.00   0.01

In [48]:
df = pd.DataFrame()

In [50]:
df.columns

RangeIndex(start=0, stop=0, step=1)